---

- name: assert | Test bareos_webui_directors
  ansible.builtin.assert:
    that:
      - bareos_webui_directors is defined
      - bareos_webui_directors is iterable
    quiet: yes

- name: assert | Test items in bareos_webui_directors are set correctly when enabled
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.enabled is defined
      - item.enabled is boolean
      - item.diraddress is defined
      - item.diraddress is string
    quiet: yes
  loop: "{{ bareos_webui_directors }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.enabled

- name: assert | Test items in bareos_webui_directors are set correctly when not enabled
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.enabled is defined
      - item.enabled is boolean
    quiet: yes
  loop: "{{ bareos_webui_directors }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - not item.enabled

- name: assert | Test bareos_webui_configuration
  ansible.builtin.assert:
    that:
      - bareos_webui_configuration is defined
      - bareos_webui_configuration is iterable
    quiet: yes
- name: assert | Test items in bareos_webui_configuration are set correctly
  ansible.builtin.assert:
    that:
      - item.section is defined
      - item.section is string
      - item.option is defined
      - item.option is string
      - item.value is defined
    quiet: yes
  loop: "{{ bareos_webui_configuration }}"
  loop_control:
    label: "{{ item.section }}:{{ item.option }}"

- name: assert | Test bareos_webui_tls_enable
  ansible.builtin.assert:
    that:
    - bareos_webui_tls_enable is defined
    - bareos_webui_tls_enable is boolean
    
- name: assert | Test bareos_webui_tls certificate configurations are set correctly
  ansible.builtin.assert:
    that:
    - item is defined
    - item is string
    loop:
      - "{{ bareos_webui_tls_ca_cert_src }}"
      - "{{ bareos_webui_tls_ca_cert_dest }}"
      - "{{ bareos_webui_tls_cert_chain_src }}"
      - "{{ bareos_webui_tls_cert_chain_dest }}"
  when: bareos_webui_tls_enable
