---
# tasks file for bareos_webui

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install requirements
  ansible.builtin.package:
    name: "{{ bareos_webui_requirements }}"

- name: Install bareos-webui
  ansible.builtin.package:
    name: bareos-webui
  notify:
    - Restart httpd

- name: Deploy directors.ini config
  ansible.builtin.template:
    src: templates/directors.ini.j2
    dest: /etc/bareos-webui/directors.ini
    backup: true
    owner: root
    group: root
    mode: "0644"

- name: Set settings for configuration.ini
  community.general.ini_file:
    path: /etc/bareos-webui/configuration.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ bareos_webui_configuration }}"
  loop_control:
    label: "{{ item.section }}:{{ item.option }}"

- name: Place TLS certificates
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ bareos_webui_httpd_user | default('http') }}"
    group: root
    mode: "0640"
    backup: true
  loop:
    - src: "{{ bareos_webui_tls_ca_cert_src }}"
      dest: "{{ bareos_webui_tls_ca_cert_dest }}"
    - src: "{{ bareos_webui_tls_cert_chain_src }}"
      dest: "{{ bareos_webui_tls_cert_chain_dest }}"
  when:
    - bareos_webui_tls_enable
    - bareos_webui_tls_ca_cert_src != ""
    - bareos_webui_tls_cert_chain_src != ""

- name: Set SELinux boolean httpd_can_network_connect
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: Enable and start HTTPD service
  ansible.builtin.service:
    name: "{{ bareos_webui_httpd_service }}"
    enabled: true
    state: started

- name: Import Lets Encrypt tasks for HTTPS
  ansible.builtin.import_tasks:
    file: letsencrypt.yml
  when:
    - bareos_webui_letsencrypt_enable
    - bareos_webui_letsencrypt_account_mail is defined
    - bareos_webui_letsencrypt_account_mail != ""
    - bareos_webui_letsencrypt_domain is defined
    - bareos_webui_letsencrypt_domain != ""
  tags:
    - role::bareos_webui
    - role::bareos_webui::letsencrypt
