---
name: Delete role from Ansible Galaxy

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  delete:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-DELETE-role.yaml@87808cf15c59f09c5e6e3b8eefedc373e4b29680 # v0.5.2
    secrets: inherit
