---
name: Release to Ansible Galaxy

on:
  release:
    types: [created, edited, published, released]

jobs:
  release:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-role.yaml@v0.1.0
    secrets: inherit
