---
name: Release to Ansible Galaxy

on:
  release:
    types: [created, edited, published, released]

jobs:
  release:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-galaxy-role-release.yaml@87808cf15c59f09c5e6e3b8eefedc373e4b29680 # v0.5.2
    secrets: inherit
