---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main
      - master

jobs:
  semantic-release:
    uses: adfinis/github-workflows-bareos/.github/workflows/semantic-release.yaml@a833edc3ef3b044b24c8d1bc942d97b6f3a0609e # v0.11.0
    secrets:
      ADFINIS_RELEASES_GITHUB_CLIENT_ID: ${{ secrets.ADFINIS_RELEASES_GITHUB_CLIENT_ID }}
      ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY: ${{ secrets.ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY }}
